require "user.options"
require "user.keymaps"
require "user.plugins"
require "user.colorscheme"
require "user.completions"
require "user.lsp"
require "user.treesitter"
require "user.telescope"
require "user.autopairs"
require "user.comment"
require "user.gitsigns"
require "user.bufferline"
require "user.null_ls"
require "user.lualine"
require "user.nvim_tree"
require "user.symbols_outline"
-- require "user.trouble"
